query getAdvertisementList{
  AdvertisementList{
    totalPages
    totalElements
    content {
      image
      updatetime
      number
      updateactorid
      type
      createtime
      time
      disabled
      webAddress
      createactorid
      id
    }
  }
}
