
mutation admin_saveEquipArg($equipArg: EquipArg_!) {
  admin_saveEquipArg(equipArg: $equipArg) {
		id
  }
}


mutation admin_importEquip($houseId: String!, $supplierId: String!, $serial: String, $rfid: String!, $location: Location_, $equipArgId: String!, $quality: Quality_!) {
  admin_importEquip(houseId: $houseId, supplierId: $supplierId, serial: $serial, rfid: $rfid, location: $location, equipArgId: $equipArgId, quality: $quality) {
    id
  }
}




query getEquip($id: String!) {
  Equip(id: $id) {
    policeId
    name
    location {
      section
      floor
      number
      surface
    }
    id
    inputTime
    quality {
      shelfLife
      productDate
    }
    equipArg {
      id
      name
      model
      imageAddress
      videoAddresses
      documentAddresses
      chargeCycle
      upkeepCycle
      category{
        id
        name
        genre{
          id
          name
        }
      }
      supplier{
        id
        phone
        name
        person
      }
    }
    state
    price
    rfid
    receiveTime
    houseId
    serial
  }
}








mutation houseUser_receiveEquip($equipIds: [String]!) {
  houseUser_receiveEquip(equipIds: $equipIds) {
    totalPages
    totalElements
    content {
      id
    }
  }
}

mutation houseUser_returnEquip($equipIds: [String]!) {
  houseUser_returnEquip(equipIds: $equipIds) {
    totalPages
    totalElements
    content {
      id
    }
  }
}



mutation admin_upkeepEquips($equipIdList: [String]!, $reason: String!, $auditor: String!) {
  admin_upkeepEquips(equipIdList: $equipIdList, reason: $reason, auditor: $auditor) {
    totalPages
    totalElements
    content {
      id
    }
  }
}



mutation admin_maintainEquips($equipIdList: [String]!, $reason: String!, $auditor: String!) {
  admin_maintainEquips(equipIdList: $equipIdList, reason: $reason, auditor: $auditor) {
    totalPages
    totalElements
    content {
      id
    }
  }
}



mutation admin_scrapEquips($equipIdList: [String]!, $reason: String!, $auditor: String!) {
  admin_scrapEquips(equipIdList: $equipIdList, reason: $reason, auditor: $auditor) {
    totalPages
    totalElements
    content {
      id
    }
  }
}




query getUserList($qfilter: qfilter) {
  UserList(qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      unitId
      policeSign
      idNumber
      name
      password
      username
      gender
      fingerprintInformation

      faceInformation
      organUnit {
        id
      }
      phone
      position
      id
      roleItems {
        roleDescribe
        roleEnum
        id
        privilegeItems {
          privilege {
            id
          }
          id
          constraintRule
        }

      }
    }
  }
}

query getCategoryList($houseId:String) {
  CategoryList(qfilter:{
      operator: EQUEAL
      key:"houseId"
      value:$houseId
  }) {
    totalPages
    totalElements
    content {
      name
      id
      categoryItems {
        name
        id
        category {
          id
        }
        equipArgs {
          id
          upkeepCycle
          name
          chargeCycle

          model
        }

      }

      houseId
    }
  }
}

query getGenreList1($houseId:String) {
  GenreList(qfilter:{
      operator: EQUEAL
      key:"categories.houseEquipArgs.houseId"
      value:$houseId
  }) {
    totalPages
    totalElements
    content {
      id
      name
      categories {
        name
        id
        houseEquipArgs {
          count
          houseId
          id
          safeStock

          equipArg {
            id
            name
          }
        }
      }

      name
    }
  }
}





query getSupplierList{
  SupplierList {
    totalPages
    totalElements
    content {
      name
      id
      person
      phone

    }
  }
}



query getEquipList($paginator: paginator, $qfilter: qfilter) {
  EquipList(paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      serial
      name
      equipArg {
        id
        model
        name
		supplier{
          name
        }
        category{
          name
          genre{
            name
          }
        }
      }
      receiveTime
      inputTime(OrderBy:DESC)
      id
      quality {
        shelfLife
        productDate
      }
      location {
        number
        floor
        surface
        section
      }
      rfid
      houseId
      state
      policeId
    }
  }
}

query getGenreList {
  GenreList{
    totalPages
    totalElements
    content {
      name
      id
      categories {
        name
        id
        equipArgs {
          category {
            id
          }
          supplier {
            id
          }
          id
          name
          chargeCycle
          model
          upkeepCycle
        }
      }
    }
  }
}


mutation category_addEquipArg($supplierId: String!, $categoryId: String!, $equipArg: EquipArg_!) {
  category_addEquipArg(supplierId: $supplierId, categoryId: $categoryId, equipArg: $equipArg) {
    id
  }
}


mutation admin_importEquips($rfids: [String]!, $price: Long!, $location: Location_, $serialList: [String], $equipArgId: String!, $quality: Quality_!) {
  admin_importEquips(rfids: $rfids, price: $price, location: $location, serialList: $serialList, equipArgId: $equipArgId, quality: $quality) {
    totalPages
    totalElements
    content {
      id
    }
  }
}



query getEquipArg($id: String!) {
  EquipArg(id: $id) {
    name
    videoAddresses
    supplier {
      id
      name
      phone
      person
    }
    id
    upkeepCycle
    model
    imageAddress
    category {
      id
      name
      genre{
        name
        id
      }
    }
    chargeCycle

    documentAddresses
  }
}


mutation category_saveEquipArg($categoryId: String!, $equipArg: EquipArg_!) {
  category_saveEquipArg(categoryId: $categoryId, equipArg: $equipArg) {
    id
  }
}

mutation admin_saveEquipInfo($equipId: String!, $location: Location_!, $quality: Quality_!) {
  admin_saveEquipInfo(equipId: $equipId, location: $location, quality: $quality) {
    id
  }
}
