query getEquipList($paginator: paginator, $qfilter: qfilter) {
  EquipList(paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      name
      state
      inputTime
      rfid
      policeId
      commonHouseId
      equipArg {
        id
      }
      serial
      id
      disabled
      quality {
        shelfLife
        productDate
      }
    }
  }
}

mutation admin_saveEquipArg($equipArg: EquipArg_!) {
  admin_saveEquipArg(equipArg: $equipArg) {
		id
  }
}


mutation admin_importEquip($serial: String, $commonHouseId: String!, $rfid: String!, $location: Location_, $equipArgId: String!, $quality: Quality_!) {
  admin_importEquip(serial: $serial, commonHouseId: $commonHouseId, rfid: $rfid, location: $location, equipArgId: $equipArgId, quality: $quality) {
    id
  }
}

query getEquip($id: String!) {
  Equip(id: $id) {
    serial
    quality {
      shelfLife
      productDate
    }
    state
    id
    inputTime
    location {
          surface
          floor
          number
    }
    equipArg {
      id
      name
      model
      manufacturer{
        person
        phone
        manufacturer
      }
      upkeepCycle
      chargeCycle
    }
    disabled
    name
    rfid
    commonHouseId
    policeId
  }
}


mutation houseUser_receiveEquip($equipIds: [String]!) {
  houseUser_receiveEquip(equipIds: $equipIds) {
    totalPages
    totalElements
    content {
      id
    }
  }
}

mutation houseUser_returnEquip($equipIds: [String]!) {
  houseUser_returnEquip(equipIds: $equipIds) {
    totalPages
    totalElements
    content {
      id
    }
  }
}



mutation admin_upkeepEquips($equipIdList: [String]!, $reason: String!, $auditor: String!) {
  admin_upkeepEquips(equipIdList: $equipIdList, reason: $reason, auditor: $auditor) {
    totalPages
    totalElements
    content {
      id
    }
  }
}



mutation admin_maintainEquips($equipIdList: [String]!, $reason: String!, $auditor: String!) {
  admin_maintainEquips(equipIdList: $equipIdList, reason: $reason, auditor: $auditor) {
    totalPages
    totalElements
    content {
      id
    }
  }
}



mutation admin_scrapEquips($equipIdList: [String]!, $reason: String!, $auditor: String!) {
  admin_scrapEquips(equipIdList: $equipIdList, reason: $reason, auditor: $auditor) {
    totalPages
    totalElements
    content {
      id
    }
  }
}




