query getEquipList($paginator: paginator, $qfilter: qfilter) {
  EquipList(paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      location {
        surface
        number
        floor
        section
      }

      disabled
      state
      name
      id
      supplier {
        id
      }
      serial
      quality {
        shelfLife
        productDate
      }
      rfid
      policeId
      equipArg {
        id
      }
      houseId
      receiveTime
      inputTime
    }
  }
}

query getEquipListDESC($paginator: paginator, $qfilter: qfilter) {
  EquipList(paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      state
      disabled
      quality {
        shelfLife
        productDate
      }
      receiveTime
      houseId

      id
      serial
      name
      policeId
      location {
        section
        floor
        number
        surface
      }
      inputTime(OrderBy:DESC)
      rfid
      supplier {
        id
      }
      equipArg {
        id
      }
    }
  }
}

query getEquipListASC($paginator: paginator, $qfilter: qfilter) {
  EquipList(paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      state
      disabled
      quality {
        shelfLife
        productDate
      }
      receiveTime
      houseId

      id
      serial
      name
      policeId
      location {
        section
        floor
        number
        surface
      }
      inputTime(OrderBy:ASC)
      rfid
      supplier {
        id
      }
      equipArg {
        id
      }
    }
  }
}
