query getEquipOperateRecordList($paginator: paginator, $qfilter: qfilter) {
  EquipOperateRecordList(paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      equipName
      equipId
      reason
      startTime
      auditor
      equipSerial
      id
      operator
      houseId
      operate

      }
      }
      }
query getEquipEventStoreList($paginator: paginator, $qfilter: qfilter) {
  EquipEventStoreList(paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      reason
      houseId
      id
      endTime

      startTime
      equipSerial
      note
      operator
      equipId
      leader
      equipName
    }
  }
}
