query getEquipList($paginator: paginator, $qfilter: qfilter) {
   EquipList(paginator: $paginator, qfilter: $qfilter) {
      totalPages
      totalElements
      content {
        id
        serial
        rfid
        state
        policeId
        inputTime
        commonHouseId
        disabled
        receiveTime
        quality {
          shelfLife
          productDate
        }
        name
        location {
          floor
          section
          surface
          number
        }
        equipArg {
          id
        }
        useCount
      }
    }
  }


query getEquipListDESC($paginator: paginator, $qfilter: qfilter) {
  EquipList(paginator: $paginator, qfilter: $qfilter) {
        totalPages
        totalElements
        content {
          id
          serial
          rfid
          state
          policeId
          inputTime
          commonHouseId
          disabled
          receiveTime
          quality {
            shelfLife
            productDate
          }
          name
          location {
            floor
            section
            surface
            number
          }
          equipArg {
            id
          }
          useCount
        }
      }
    }

query getEquipListASC($paginator: paginator, $qfilter: qfilter) {
  EquipList(paginator: $paginator, qfilter: $qfilter) {
        totalPages
        totalElements
        content {
          id
          serial
          rfid
          state
          policeId
          inputTime
          commonHouseId
          disabled
          receiveTime
          quality {
            shelfLife
            productDate
          }
          name
          location {
            floor
            section
            surface
            number
          }
          equipArg {
            id
          }
          useCount
        }
      }
    }