query getEquipList($paginator: paginator, $qfilter: qfilter) {
  EquipList(paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      inputTime
      receiveTime
      quality {
        productDate
        shelfLife
      }
      equipArg {
        id
        name
        model
      }
      policeId
      houseId
      id
      name
      disabled
      state
      serial
      location {
        section
        floor
        number
        surface
      }
      rfid
    }
  }
}


query getEquipList1 {
  EquipList {
    totalPages
    totalElements
    content {
      location {
        surface
        number
      }
      equipArg {
        id
      	name
        model
      }
      name
      id
    }
  }
}



