query getUserList($id:String,$paginator: paginator) {
  UserList(qfilter:{
    key:"organUnit.id",
    operator:EQUEAL
    value:$id
    combinator:AND
    next:{
      key:"disabled",
      operator:EQUEAL
      value:"false"
    }
  }
    paginator: $paginator) {
    totalPages
    totalElements
    content {
      disabled
      password
      policeSign
      idNumber
      id
      phone
      organUnit {
        id
      }
      fingerprintInformation
      faceInformation
      roleItems {
        disabled
        id
        privilegeItems {
          id
          constraintRule
          privilege {
            id
          }
        }
        roleEnum
      }
      gender
      name
      username
      position
    }
  }
}
mutation identitySaveUser($user: User_!) {
  identity_saveUser(user: $user) {
    unitId
    disabled
    policeSign
    id
    organUnit {
      id
    }
    faceInformation
    name
    gender
    roleItems {
      disabled
      id
      privilegeItems {
        privilege {
          id
        }
        id
        constraintRule
      }
      roleEnum
      roleDescribe
    }
    fingerprintInformation
    username
    position
    password
    idNumber
    phone
  }
}

