query getMessageList11($id:String) {
  MessageList(qfilter:{
    combinator:AND
    key:"userId"
    operator:LIKE
    value:$id
  }){
    totalPages
    totalElements
    content {
      id
      userId
      content
      disabled
      time(OrderBy:DESC)
      sendUserId
      readed
      title
      type
    }
  }
}


query getMessageList($qfilter: qfilter) {
  MessageList(qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      sendUserId
      type
      disabled
      userId
      id
      content
      title
      readed
      time(OrderBy:DESC)
    }
  }
}






mutation houseUser_readMessage($messageId: String!) {
  houseUser_readMessage(messageId: $messageId)
}
