query getMessageList11($id:String) {
  MessageList(qfilter:{
    combinator:AND
    key:"userId"
    operator:LIKE
    value:$id
  }){
    totalPages
    totalElements
    content {
      id
      userId
      content
      time(OrderBy:DESC)
      sendUserId
      readed
      title
      type
    }
  }
}


query getMessageList($qfilter: qfilter) {
  MessageList(qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      sendUserId
      type

      userId
      id
      content
      title
      readed
      time(OrderBy:DESC)
    }
  }
}


query getMessageList2($paginator: paginator,$qfilter: qfilter) {
  MessageList(paginator: $paginator,qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      sendUserId
      type

      userId
      id
      content
      title
      readed
      time(OrderBy:DESC)
    }
  }
}







mutation houseUser_readMessage($messageId: String!) {
  houseUser_readMessage(messageId: $messageId)
}
