query getOrganUnitListList ($key:String!,$value:String!){
  OrganUnitList(qfilter: {key: $key, value: $value, operator: EQUEAL}) {
    content {
      id
      level
      name
      location
      organUnitSet {
          id
          level
          name
          location
          organUnitSet{
            level
            name
            id
          }
      }
    }
  }
}

mutation architectureSaveOrganUnit($organUnit: OrganUnit_!) {
  architecture_saveOrganUnit(organUnit: $organUnit) {
    organUnitSet {
          id
        }
    id
    location
    level
    name

    organUnit {
          id
        }
  }
}
