query RoleList($paginator: paginator){
  RoleList(paginator:$paginator){
    totalPages
    totalElements
    content{
      id
      name
      number
      createtime
      privilegeItems{
        id
        constraintRule
        privilege{
          id
          name
          number
          privilege
          category
        }
      }
    }
  }
}


query PrivilegeList($paginator: paginator){
  PrivilegeList(paginator:$paginator){
    totalPages
    totalElements
    content{
      id
      name
    }
  }
}

mutation addRole($role: Role_!){
  role_add(role:$role){
    id
  }
}

mutation updateRole($role: Role_!){
  role_update(role:$role){
    id
  }
}
