query getEquipArgList($qfilter: qfilter) {
  EquipArgList(qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      id
      category {
        id
        name
        genre{
          name
        }
      }
      supplier {
        id
      }
      model
      upkeepCycle
      name
      chargeCycle
      disabled
    }
  }
}
