query getEquipArgList($qfilter: qfilter) {
  EquipArgList(qfilter: $qfilter) {
    totalPages
    totalElements
    content {
          upkeepCycle
          supplier {
            id
          }
          model
          chargeCycle
          disabled
          name
          id
          imageAddress
          videoAddresses
          category {
            id
          }
          documentAddresses
    }
  }
}
