query getOrganUnit ($key:String!,$value:String!){
  OrganUnitList(qfilter: {key: $key, value: $value, operator: EQUEAL}) {
    content {
     location
           name
           ip
           upperId
            houseSet{
            id
            name
            }
           level
           id
    }
  }
}

query getUserList($qfilter: qfilter) {
  UserList(qfilter:$qfilter) {
    totalPages
    totalElements
    content {
      unitId
      role {
        id
      }
      id
      name
    }
  }
}
