query getUserList($paginator: paginator, $qfilter: qfilter) {
  UserList(paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      faceInformation
            name
            idNumber
            fingerprintInformation
            position
            password
            role {
              id
              roleDescribe
              roleEnum
            }
            id
            phone
            unitId
            policeSign
            gender
    }
  }
}

query getRoleList{
  RoleList{
    totalPages
    totalElements
    content {
      roleDescribe
      id
      roleEnum
    }
  }
}

query getOrganUnit($id: String!) {
  OrganUnit(id: $id) {
    location
    id
    ip
    level
    name
  }
}
mutation identityTriggerSyncFaceInfo {
  identity_triggerSyncFaceInfo {
    faceInformation
    gender
    name
    policeSign
    position
    fingerprintInformation
    phone
    password
    role {
      id
    }
    unitId
    id
    idNumber
    sign
  }
}

mutation identitySaveUser($user: User_!) {
  identity_saveUser(user: $user) {
    faceInformation
        unitId
        password
        policeSign
        idNumber
        role {
          id
        }
        position
        phone
        id
        gender
        name
        fingerprintInformation
  }
}
mutation identityUpdateUser($user: User_!) {
  identity_updateUser(user: $user) {
   faceInformation
           unitId
           password
           policeSign
           idNumber
           role {
             id
           }
           position
           phone
           id
           gender
           name
           fingerprintInformation
  }
}

