query getUserList($paginator: paginator, $qfilter: qfilter) {
  UserList(paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      password
      idNumber
      position
      policeSign
      faceInformation
      name
      gender

      fingerprintInformation
      unitId
      phone
      id
      organUnit {
        id
        name
      }
      roleItems {

        id
        privilegeItems {
          constraintRule
          id
          privilege {
            id
          }
        }
        roleEnum
        roleDescribe
      }
    }
  }
}

query getRoleList{
  RoleList{
    totalPages
    totalElements
    content {

      id
      privilegeItems {
        constraintRule
        id
        privilege {
          id
        }
      }
      roleEnum
      roleDescribe
    }
  }
}

mutation identitySaveUser($user: User_!) {
  identity_saveUser(user: $user) {
    roleItems {

      privilegeItems {
        constraintRule
        privilege {
          id
        }
        id
      }
      roleEnum
      roleDescribe
      id
    }
    idNumber
    name
    id
    unitId
    fingerprintInformation
    gender
    organUnit {
      id
    }

    password
    position
    policeSign
    phone
    faceInformation
  }
}
mutation identityUpdateUser($user: User_!) {
  identity_updateUser(user: $user) {
    fingerprintInformation

    position
    id
    policeSign
    phone
    password
    gender
    faceInformation
    unitId
    idNumber
    organUnit {
      id
    }
    roleItems {
      roleDescribe

      id
      roleEnum
      privilegeItems {
        privilege {
          id
        }
        constraintRule
        id
      }
    }
    name
  }
}

