mutation categoryInit($organUnitId: String!) {
  category_init(organUnitId: $organUnitId) {
    totalPages
    totalElements
    content {
      organUnitId
      id
      name
      categoryItems {
        id
        name
        itemEquipArgs {
          equipArg {
            id
          }
          id
          safeSock
          categoryItem {
            id
          }

        }
        category {
          id
        }

      }

    }
  }
}



query getCategoryList($id: String!){
  CategoryList(qfilter: {key:"houseId", value: $id, operator: EQUEAL}) {
    totalPages
    totalElements
    content {
      id

      houseId
      name
      categoryItems {
        category {
          id
        }
        id
        equipArgs {
          id

          name
          model
          upkeepCycle
          chargeCycle
        }

        name
      }
    }
  }
}


query getHouseEquipArgList($paginator: paginator, $qfilter: qfilter) {
EquipArgList(paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      id
      category {
        id
        name
        genre{
          name
        }
      }
      supplier {
        id
      }
      model
      upkeepCycle
      name
      chargeCycle

    }
  }
}





query getCommonHouseList($id:String!){
  CommonHouseList(qfilter: {key:"organUnitId", value: $id, operator: EQUEAL}){
    totalPages
    totalElements
    content {
           id

           name
           environmentInfo
           organUnitId
    }
  }
}


mutation commonHouseSaveCommonHouse($organUnitId: String!, $name: String!) {
  commonHouse_saveCommonHouse(organUnitId: $organUnitId, name: $name) {

    name
    id
    organUnitId
    environmentInfo
  }
}


mutation categoryAddCategoryItem($name: String!, $categoryId: String!) {
  category_addCategoryItem(name: $name, categoryId: $categoryId) {
    itemEquipArgs {
      categoryItem {
        id
      }

      equipArg {
        id
      }
      safeSock
      id
    }

    name
    category {
      id
    }
    id
  }
}

mutation categoryAddItemEquipArg($categoryItemId: String!, $safeSock: Int!, $equipArgId: String!) {
  category_addItemEquipArg(categoryItemId: $categoryItemId, safeSock: $safeSock, equipArgId: $equipArgId) {
    itemEquipArgs {
      categoryItem {
        id
      }

      equipArg {
        id
      }
      safeSock
      id
    }

    name
    category {
      id
    }
    id
  }
}

mutation categorySave($category: Category_!) {
  category_save(category: $category) {

    id
    name
    type
  }
}



mutation suppliers_saveSupplier($supplier: Supplier_!) {
  suppliers_saveSupplier(supplier: $supplier) {
    id
  }
}

query getSupplierList($paginator: paginator, $qfilter: qfilter) {
  SupplierList(paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      id
      phone
      name
      person

    }
  }
}



query getEquipArgList($paginator: paginator, $qfilter: qfilter) {
  EquipArgList(paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      upkeepCycle
      id
      imageAddress
      videoAddresses
      documentAddresses
      name
      model

      chargeCycle
      supplier {
        id
        phone
        person
        name
      }
      category {
        id
        name
      	genre{
          id
          name
        }
      }
    }
  }
}

query getHouseStockList($paginator: paginator, $qfilter: qfilter) {
  HouseStockList (paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      safeStock

      id
      equipArg {
        id
        name
        model
        supplier{
          id
          name
        }
        category{
          id
          name
        	genre{
            id
            name
          }
        }
      }
      houseId
      count
    }
  }
}



mutation house_changeSafeSock($houseEquipArgId: String!, $safeSock: Int!) {
  house_changeSafeSock(houseEquipArgId: $houseEquipArgId, safeSock: $safeSock) {
    id
  }
}


mutation admin_importEquips($rfids: [String]!, $location: Location_, $serialList: [String], $equipArgId: String!, $quality: Quality_!) {
  admin_importEquips(rfids: $rfids, location: $location, serialList: $serialList, equipArgId: $equipArgId, quality: $quality) {
    totalPages
    totalElements
    content {
      id
    }
  }
}


mutation suppliers_deleteSupplier($supplierId: String!) {
  suppliers_deleteSupplier(supplierId: $supplierId)
}
