mutation categoryInit($organUnitId: String!) {
  category_init(organUnitId: $organUnitId) {
    totalPages
    totalElements
    content {
      organUnitId
      id
      name
      categoryItems {
        id
        name
        itemEquipArgs {
          equipArg {
            id
          }
          id
          safeSock
          categoryItem {
            id
          }
          disabled
        }
        category {
          id
        }
        disabled
      }
      disabled
    }
  }
}

query getCategoryList($qfilter: qfilter) {
  CategoryList (qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      organUnitId
      id
      name
      categoryItems {
        id
        name
        itemEquipArgs {
          equipArg {
            id
          }
          id
          safeSock
          categoryItem {
            id
          }
          disabled
        }
        category {
          id
        }
        disabled
      }
      disabled
    }
  }
}




query getCommonHouseList($id:String!){
  CommonHouseList(qfilter: {key:"organUnitId", value: $id, operator: EQUEAL}){
    totalPages
    totalElements
    content {
           id
           disabled
           name
           environmentInfo
           organUnitId
    }
  }
}


mutation commonHouseSaveCommonHouse($organUnitId: String!, $name: String!) {
  commonHouse_saveCommonHouse(organUnitId: $organUnitId, name: $name) {
    disabled
    name
    id
    organUnitId
    environmentInfo
  }
}


mutation categoryAddCategoryItem($name: String!, $categoryId: String!) {
  category_addCategoryItem(name: $name, categoryId: $categoryId) {
    itemEquipArgs {
      categoryItem {
        id
      }
      disabled
      equipArg {
        id
      }
      safeSock
      id
    }
    disabled
    name
    category {
      id
    }
    id
  }
}

mutation categoryAddItemEquipArg($categoryItemId: String!, $safeSock: Int!, $equipArgId: String!) {
  category_addItemEquipArg(categoryItemId: $categoryItemId, safeSock: $safeSock, equipArgId: $equipArgId) {
    itemEquipArgs {
      categoryItem {
        id
      }
      disabled
      equipArg {
        id
      }
      safeSock
      id
    }
    disabled
    name
    category {
      id
    }
    id
  }
}


mutation suppliers_saveSupplier($supplier: Supplier_!) {
  suppliers_saveSupplier(supplier: $supplier) {
    id
  }
}

query getSupplierList($paginator: paginator, $qfilter: qfilter) {
  SupplierList(paginator: $paginator, qfilter: $qfilter) {
    totalPages
    totalElements
    content {
      id
      phone
      name
      person
      disabled
    }
  }
}



